channels:
- conda-forge
dependencies:
- python=3.8.5
- pip<=20.1.1
- pip:
  - mlflow==1.30.0
  - numpy==1.21.6
  - cloudpickle==1.6.0
  - scikit-learn==0.22.1
  - azureml-defaults==1.38.0
  - azureml-core==1.38.0
  - azureml-contrib-services==1.38.0
  - azureml-ai-monitoring~=0.1.0b1
  - azureml-inference-server-http==0.8.0
  - pandas==1.5.3
name: mlflow-env